version: "3.9"

services:
  api:
    build: .
    container_name: blog_api
    restart: always
    env_file: .env
    environment:
      # Explicitly specify Cloudinary variables to ensure they're passed correctly
      CLOUD_NAME: ${CLOUD_NAME}
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      # Use Railway database directly instead of local postgres
      DATABASE_URL: ${DATABASE_URL}
    command: bash -c "./run_migrations.sh && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"

  pgadmin: # Thêm service pgAdmin
    image: dpage/pgadmin4
    container_name: my_pgadmin
    restart: always
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL} # Thêm vào file .env
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} # Thêm vào file .env
    ports:
      - "5050:80" # Truy cập pgAdmin qua http://localhost:5050

volumes:
  pgadmin_data:
